Executable  = script_data.sh
Universe    = vanilla
notification= Never
Input       = /dev/null
Arguments       = $(runnumber) 
Initialdir    = /sphenix/user/samfred/run25/ppg11/histmaking
Output    = $(Initialdir)/log/$(runnumber).out
Error     = $(Initialdir)/log/$(runnumber).err
Log       = tmp/$(runnumber).log
PeriodicHold  = (NumJobStarts>=1 && JobStatus == 1)
job_lease_duration = 3600

Queue runnumber from runlist_data.list

