Executable  = script.sh
Universe    = vanilla
notification= Never
Input       = /dev/null
Arguments       = $(runnumber) $(trigger) 
Initialdir    = /sphenix/user/samfred/run25/ppg11/histmaking
Output    = $(Initialdir)/log/$(runnumber)$(trigger).out
Error     = $(Initialdir)/log/$(runnumber)$(trigger).err
Log       = tmp/$(runnumber).log
PeriodicHold  = (NumJobStarts>=1 && JobStatus == 1)
job_lease_duration = 3600

Queue runnumber,trigger from runlist.list

