Executable  = script.sh
Universe    = vanilla
notification= Never
Input       = /dev/null
Arguments       = $(trigger) $(filename)
Initialdir    = /sphenix/user/samfred/run25/ppg11/treemaking/macros
Output    = $(Initialdir)/log/$(trigger)_$(filename).out
Error     = $(Initialdir)/log/$(trigger)_$(filename).err
Log       = /tmp/samfred/$(process).log
PeriodicHold  = (NumJobStarts>=1 && JobStatus == 1)
job_lease_duration = 3600

Queue trigger, filename from queue.list

