Executable  = script.sh
Universe    = vanilla
notification= Never
Input       = /dev/null
Arguments       = $(particle) $(type) $(seg) 
Initialdir    = /sphenix/user/samfred/run25/ppg11/Corrections
Output    = $(Initialdir)/log/$(particle)$(seg).out
Error     = $(Initialdir)/log/$(particle)$(seg).err
Log       = tmp/$(particle)$(seg).log
PeriodicHold  = (NumJobStarts>=1 && JobStatus == 1)
job_lease_duration = 3600

Queue particle,type,seg from args.txt

